name: mind_buddy
description: Mind Buddy app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  flutter_quill: ^10.0.0
  image_picker: ^1.1.2
  file_picker: ^8.0.6
  path_provider: ^2.1.4


  # ğŸŒ Networking
  http: ^1.2.2
  dio: ^5.7.0

  # â˜ï¸ Backend & auth
  supabase_flutter: ^2.5.6

  # ğŸŒ± State management
  flutter_riverpod: ^2.5.1
  provider: ^6.0.0

  # ğŸ§­ Navigation
  go_router: ^14.2.7

  # ğŸ” Secure local storage
  flutter_secure_storage: ^9.2.2

  # ğŸ’¾ Simple key-value storage
  shared_preferences: ^2.3.3

  # ğŸ§¾ App version info
  package_info_plus: ^8.0.2

  # ğŸ”— Open URLs
  url_launcher: ^6.3.1

  # ğŸ†” Generate unique IDs
  uuid: ^4.5.1

  table_calendar: ^3.1.2
  equatable: ^2.0.7
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
